# Makefile for abprint
#CHANGED TO JAKESHOWCHARS AND MUST BE CHANGED BACK TO REGULAR SHOW CHARS
PROGRAM = showchars
SOURCES = showchars.c
OBJECTS = showchars.o
CFLAGS  = -O

.SUFFIXES:
.SUFFIXES: .c .o

.c.o : ; cc $(CFLAGS) -c $< 

$(PROGRAM) : $(OBJECTS)
	cc -o $@ $(CFLAGS) $(OBJECTS)

clean: ; /bin/rm -f $(PROGRAM) $(OBJECTS)

depend : $(SOURCES)
	makedepend $(SOURCES) -I/usr/include/linux -I/usr/lib/gcc/x86_64-redhat-linux/3.4.6/include




# DO NOT DELETE

showchars.o: /usr/include/stdio.h /usr/include/bits/libc-header-start.h
showchars.o: /usr/include/features.h /usr/include/stdc-predef.h
showchars.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
showchars.o: /usr/include/bits/long-double.h /usr/include/gnu/stubs.h
showchars.o: /usr/include/linux/stddef.h
showchars.o: /usr/lib/gcc/x86_64-redhat-linux/3.4.6/include/stdarg.h
showchars.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
showchars.o: /usr/include/bits/types/__fpos_t.h
showchars.o: /usr/include/bits/types/__mbstate_t.h
showchars.o: /usr/include/bits/types/__fpos64_t.h
showchars.o: /usr/include/bits/types/__FILE.h /usr/include/bits/types/FILE.h
showchars.o: /usr/include/bits/types/struct_FILE.h
showchars.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
showchars.o: /usr/include/stdlib.h /usr/include/bits/waitflags.h
showchars.o: /usr/include/bits/waitstatus.h /usr/include/bits/floatn.h
showchars.o: /usr/include/bits/floatn-common.h /usr/include/sys/types.h
showchars.o: /usr/include/bits/types/clock_t.h
showchars.o: /usr/include/bits/types/clockid_t.h
showchars.o: /usr/include/bits/types/time_t.h
showchars.o: /usr/include/bits/types/timer_t.h
showchars.o: /usr/include/bits/stdint-intn.h /usr/include/endian.h
showchars.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
showchars.o: /usr/include/bits/uintn-identity.h /usr/include/sys/select.h
showchars.o: /usr/include/bits/select.h /usr/include/bits/types/sigset_t.h
showchars.o: /usr/include/bits/types/__sigset_t.h
showchars.o: /usr/include/bits/types/struct_timeval.h
showchars.o: /usr/include/bits/types/struct_timespec.h
showchars.o: /usr/include/bits/pthreadtypes.h
showchars.o: /usr/include/bits/thread-shared-types.h
showchars.o: /usr/include/bits/pthreadtypes-arch.h /usr/include/alloca.h
showchars.o: /usr/include/bits/stdlib-float.h /usr/include/linux/string.h
showchars.o: Chars/All_Chars.h Chars/Char_20.h Chars/Char_21.h
showchars.o: Chars/Char_22.h Chars/Char_23.h Chars/Char_24.h Chars/Char_25.h
showchars.o: Chars/Char_26.h Chars/Char_27.h Chars/Char_28.h Chars/Char_29.h
showchars.o: Chars/Char_2A.h Chars/Char_2B.h Chars/Char_2C.h Chars/Char_2D.h
showchars.o: Chars/Char_2E.h Chars/Char_2F.h Chars/Char_30.h Chars/Char_31.h
showchars.o: Chars/Char_32.h Chars/Char_33.h Chars/Char_34.h Chars/Char_35.h
showchars.o: Chars/Char_36.h Chars/Char_37.h Chars/Char_38.h Chars/Char_39.h
showchars.o: Chars/Char_3A.h Chars/Char_3B.h Chars/Char_3C.h Chars/Char_3D.h
showchars.o: Chars/Char_3E.h Chars/Char_3F.h Chars/Char_40.h Chars/Char_41.h
showchars.o: Chars/Char_42.h Chars/Char_43.h Chars/Char_44.h Chars/Char_45.h
showchars.o: Chars/Char_46.h Chars/Char_47.h Chars/Char_48.h Chars/Char_49.h
showchars.o: Chars/Char_4A.h Chars/Char_4B.h Chars/Char_4C.h Chars/Char_4D.h
showchars.o: Chars/Char_4E.h Chars/Char_4F.h Chars/Char_50.h Chars/Char_51.h
showchars.o: Chars/Char_52.h Chars/Char_53.h Chars/Char_54.h Chars/Char_55.h
showchars.o: Chars/Char_56.h Chars/Char_57.h Chars/Char_58.h Chars/Char_59.h
showchars.o: Chars/Char_5A.h Chars/Char_5B.h Chars/Char_5C.h Chars/Char_5D.h
showchars.o: Chars/Char_5E.h Chars/Char_5F.h Chars/Char_60.h Chars/Char_61.h
showchars.o: Chars/Char_62.h Chars/Char_63.h Chars/Char_64.h Chars/Char_65.h
showchars.o: Chars/Char_66.h Chars/Char_67.h Chars/Char_68.h Chars/Char_69.h
showchars.o: Chars/Char_6A.h Chars/Char_6B.h Chars/Char_6C.h Chars/Char_6D.h
showchars.o: Chars/Char_6E.h Chars/Char_6F.h Chars/Char_70.h Chars/Char_71.h
showchars.o: Chars/Char_72.h Chars/Char_73.h Chars/Char_74.h Chars/Char_75.h
showchars.o: Chars/Char_76.h Chars/Char_77.h Chars/Char_78.h Chars/Char_79.h
showchars.o: Chars/Char_7A.h Chars/Char_7B.h Chars/Char_7C.h Chars/Char_7D.h
showchars.o: Chars/Char_7E.h
