#! /bin/bash

# Using $(), we can run a command and collect the output
# This works even with commands that are pipes.

for file in *
do
    # Using grep to get what is after Modify in the
    # stat program
    filetime=$(stat $file | grep -i modify | sed 's/[^:]*://')

    echo $filetime " -- "  $file
done
